Environment Variables
aahana2410/FoodChive-320 pull request #7
Opened 2022-11-08 04:35 UTC by RyeCai

Set up development and production environment

2022-11-08 05:06 UTC, RiyanFarhat requested changes
Check comment at line 32 of RecipeList.js

2022-11-10 02:41 UTC, estevens2319 approved these changes

2022-11-10 02:43 UTC, estevens2319 approved these changes

2022-11-10 03:10 UTC, RiyanFarhat approved these changes
LGTM!

2022-11-10 03:12 UTC, merged